apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: isidorus
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  serviceName: minio
  selector:
    matchLabels:
      io.kompose.service: minio
  template:
    metadata:
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: testpassword123
            - name: MINIO_ROOT_USER
              value: test
          image: minio/minio
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: minio
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
