receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  logging:
    verbosity: detailed
  otlp/signoz:
    endpoint: signoz-otel-collector:4317
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, logging, otlp/signoz]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, logging]
  telemetry:
    logs:
      level: "info"
