apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: isidorus
  annotations:
    kompose.cmd: kompose convert -f docker-compose.base.yml -f docker-compose.prod.yml -o k8s/base/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: image-extractor-worker
  name: image-extractor-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: image-extractor-worker
  template:
    metadata:
  namespace: isidorus
      annotations:
        kompose.cmd: kompose convert -f docker-compose.base.yml -f docker-compose.prod.yml -o k8s/base/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: image-extractor-worker
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              value: test
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              value: testpassword123
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres.isidorus.svc.cluster.local:5432/isidorus
            - name: IMAGES_BUCKET
              value: isidorus-images
            - name: IMAGE_EXPLAINER_ENABLED
              value: "false"
            - name: IMAGE_EXPL_QUEUE_URL
              value: http://elasticmq.isidorus.svc.cluster.local:9324/000000000000/image-explainer-queue
            - name: INPUT_QUEUE_URL
              value: http://elasticmq.isidorus.svc.cluster.local:9324/000000000000/image-extractor-queue
            - name: S3_ENDPOINT_URL
              value: http://minio.isidorus.svc.cluster.local:9000
            - name: SQS_ENDPOINT_URL
              value: http://elasticmq.isidorus.svc.cluster.local:9324
            - name: WRITER_QUEUE_URL
              value: http://elasticmq.isidorus.svc.cluster.local:9324/000000000000/writer-queue
          image: image-extractor-worker
          name: image-extractor-worker
      restartPolicy: Always
