apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: indexer-scaler
  namespace: isidorus
spec:
  scaleTargetRef:
    name: indexer-worker
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: aws-sqs
      metadata:
        queueURL: http://elasticmq:9324/000000000000/indexer-queue
        queueLength: "10"
        awsRegion: us-east-1
        awsEndpoint: http://elasticmq:9324
      authenticationRef:
        name: keda-aws-secrets
