apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: writer-scaler
  namespace: isidorus
spec:
  scaleTargetRef:
    name: writer-worker
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: http://elasticmq.isidorus.svc.cluster.local:9324/000000000000/writer-queue
        queueLength: "10"
        awsRegion: us-east-1
        awsEndpoint: http://elasticmq.isidorus.svc.cluster.local:9324
      authenticationRef:
        name: keda-aws-secrets
