name: Docker Hub Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean up Docker Hub
        shell: bash
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: ./scripts/dockerhub-cleanup.sh
